[project]
name = "my-minecraft-modpack"
minecraft-version = ">=1.20.1"
mods = [
    "ad-astra",
    "ae2",
    "aeroblender",
    "aether",
    "aether-lost-content",
    "ai-improvements",
    "alexs-caves",
    "alternate-current",
    "appleskin",
    "archers-paradox",
    "architectury-api",
    "ars-creo",
    "ars-nouveau",
    "ars-ocultas",
    "balm",
    "bellsandwhistles",
    "better-advancements",
    "better-archeology",
    "better-beds-reforged",
    "better-f3",
    "better-third-person",
    "blood-magic",
    "blue-skies",
    "bosses-of-mass-destruction-forge",
    "botarium",
    "breezy",
    "bucketlib",
    "caelus",
    "canary",
    "ceramic-bucket",
    "cerbons-api",
    "chalk-mod",
    "chat-heads",
    "chefs-delight",
    "citadel",
    "cloth-config",
    "coffee-delight",
    "cofh-core",
    "collective",
    "common-network",
    "connector",
    "crafting-tweaks",
    "create",
    "create-big-cannons",
    "create-central-kitchen",
    "create-new-age",
    "create-oppenheimered",
    "create-steam-n-rails",
    "create-wizardry",
    "createaddition",
    "cristel-lib",
    "ct-overhaul-village",
    "ctov-beautify-compat",
    "ctov-chefs-delight-compat",
    "ctov-farmers-delight-compat",
    "ctov-immersive-engineering-compat",
    "ctov-irons-spells-n-spellbooks-compat",
    "curios",
    "deep-aether",
    "destroy",
    "distanthorizons",
    "do-a-barrel-roll",
    "do-api",
    "e4mc",
    "easy-anvils",
    "easy-magic",
    "easy-shulker-boxes",
    "embeddium",
    "ends-delight",
    "entityculling",
    "exposure",
    "festive-delight",
    "forgified-fabric-api",
    "gravestone-mod",
    "guard-villagers",
    "ice-and-fire-dragons",
    "immediatelyfast",
    "immersive-ui",
    "immersiveengineering",
    "incendium",
    "insanelib",
    "irons-spells-n-spellbooks",
    "jei",
    "just-enough-archaeology",
    "just-enough-effect-descriptions-jeed",
    "just-enough-professions-jep",
    "just-enough-resources-jer",
    "justenoughbreeding",
    "kotlin-for-forge",
    "l_enders-cataclysm",
    "lets-do-bakery",
    "lets-do-beachparty",
    "lets-do-candlelight",
    "lets-do-herbalbrews",
    "lets-do-meadow",
    "lets-do-nethervinery",
    "lets-do-vinery",
    "libx",
    "lionfish-api",
    "lithostitched",
    "lootr",
    "memoryleakfix",
    "miners-delight",
    "modonomicon",
    "morechathistory-reforged",
    "mouse-tweaks",
    "nethers-delight",
    "no-chat-reports",
    "noisium",
    "not-enough-animations",
    "notenoughcrashes",
    "nullscape",
    "occultism",
    "oceans-delight",
    "octo-lib",
    "oculus",
    "open-parties-and-claims",
    "patchouli",
    "pick-up-notifier",
    "playeranimator",
    "plushie",
    "progressive-bosses",
    "puzzles-lib",
    "quark",
    "quark-oddities",
    "regions-unexplored",
    "remove-terralith-intro-message",
    "resourceful-config",
    "resourceful-lib",
    "rubidium-extra",
    "saturn",
    "smartbrainlib",
    "sound-physics-remastered",
    "structure-gel-api",
    "supermartijn642s-config-lib",
    "terrablender",
    "terralith",
    "terralith-biome-saplings",
    "the-lost-castle",
    "the-one-probe",
    "tome-of-blood-rebirth",
    "totw-modded",
    "towns-and-towers",
    "trashslot",
    "travelersbackpack",
    "tree-harvester",
    "twilight-delight",
    "twilight-forest-the-lost-blocks",
    "upcycle!",
    "useful-slime",
    "vegan-delight",
    "visuality-forge",
    "waystones",
    "waystones-teleport-pets",
    "when-dungeons-arise",
    "wits",
    "xaeros-minimap",
    "xaeros-minimap-world-map-waystones-compatibility-forge",
    "xaeros-world-map",
    "yungs-api",
    "yungs-better-desert-temples",
    "yungs-better-dungeons",
    "yungs-better-jungle-temples",
    "yungs-better-mineshafts",
    "yungs-better-nether-fortresses",
    "yungs-better-ocean-monuments",
    "yungs-better-strongholds",
    "yungs-better-witch-huts",
    "yungs-bridges",
    "yungs-extras",
    "zeta",
]
