[project]
name = "Fabulously Optimized"
minecraft-version = ">=1.20.1"
mods = [
    "better-mount-hud",
    "bettergrassify",
    "capes",
    "cloth-config",
    "continuity",
    "controlify",
    "cubes-without-borders",
    "debugify",
    "distanthorizons",
    "dynamic-fps",
    "e4mc",
    "ebe",
    "entity-model-features",
    "entityculling",
    "entitytexturefeatures",
    "fabric-api",
    "fabric-language-kotlin",
    "fabrishot",
    "fastquit",
    "ferrite-core",
    "forge-config-api-port",
    "immediatelyfast",
    "iris",
    "lambdynamiclights",
    "language-reload",
    "lithium",
    "main-menu-credits",
    "mixintrace",
    "modelfix",
    "modernfix",
    "modmenu",
    "morechathistory",
    "moreculling",
    "no-chat-reports",
    "optigui",
    "paginatedadvancements",
    "polytone",
    "puzzle",
    "reeses-sodium-options",
    "rrls",
    "sodium",
    "sodium-extra",
    "xaeros-minimap",
    "xaeros-world-map",
    "yacl",
    "yosbr",
    "zoomify",
]
